name: Release

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore
        run: dotnet restore

      - name: Publish API
        run: dotnet publish src/ShopSphere.Api/ShopSphere.Api.csproj -c Release -o publish

      - name: Upload Publish Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ShopSphere-API
          path: publish